INSERT INTO Estados (Nome,Sigla) VALUES ('Acre','AC')
INSERT INTO Estados (Nome,Sigla) VALUES ('Alagoas','AL')
INSERT INTO Estados (Nome,Sigla) VALUES ('Amapá','AP')
INSERT INTO Estados (Nome,Sigla) VALUES ('Amazonas','AM')
INSERT INTO Estados (Nome,Sigla) VALUES ('Bahia','BA')
INSERT INTO Estados (Nome,Sigla) VALUES ('Ceará','CE')
INSERT INTO Estados (Nome,Sigla) VALUES ('Distrito Federal','DF')
INSERT INTO Estados (Nome,Sigla) VALUES ('Espírito Santo','ES')
INSERT INTO Estados (Nome,Sigla) VALUES ('Goiás','GO')
INSERT INTO Estados (Nome,Sigla) VALUES ('Maranhão','MA')
INSERT INTO Estados (Nome,Sigla) VALUES ('Mato Grosso','MT')
INSERT INTO Estados (Nome,Sigla) VALUES ('Mato Grosso do Sul','MS')
INSERT INTO Estados (Nome,Sigla) VALUES ('Minas Gerais','MG')
INSERT INTO Estados (Nome,Sigla) VALUES ('Pará','PA')
INSERT INTO Estados (Nome,Sigla) VALUES ('Paraíba','PB')
INSERT INTO Estados (Nome,Sigla) VALUES ('Paraná','PR')
INSERT INTO Estados (Nome,Sigla) VALUES ('Pernambuco','PE')
INSERT INTO Estados (Nome,Sigla) VALUES ('Piauí','PI')
INSERT INTO Estados (Nome,Sigla) VALUES ('Rio de Janeiro','RJ')
INSERT INTO Estados (Nome,Sigla) VALUES ('Rio Grande do Norte','RN')
INSERT INTO Estados (Nome,Sigla) VALUES ('Rio Grande do Sul','RS')
INSERT INTO Estados (Nome,Sigla) VALUES ('Rondônia','RO')
INSERT INTO Estados (Nome,Sigla) VALUES ('Roraima','RR')
INSERT INTO Estados (Nome,Sigla) VALUES ('Santa Catarina','SC')
INSERT INTO Estados (Nome,Sigla) VALUES ('São Paulo','SP')
INSERT INTO Estados (Nome,Sigla) VALUES ('Sergipe','SE')
INSERT INTO Estados (Nome,Sigla) VALUES ('Tocantins','TO')
INSERT INTO Estados (Nome,Sigla) VALUES ('Exterior','EX')
